config/routes.rb
Rails.application.routes.draw do

  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  mount GlacierOnRails::Engine, at: '/'

  scope "/:locale" do
    get 'home', :to => 'home#index'
    mount AcmePlugin::Engine, at: '/'
    resources :csp_reports, :only => [:index, :create]
    get 'csp_reports/clear_all', :to => 'csp_reports#clear_all', :via => :get
    exceptions = [:not_found, :method_not_allowed, :not_implemented, :not_acceptable, :unprocessable_entity, :bad_request, :conflict]
    exceptions.each do |exception|
      get exception, :to => "errors##{exception}"
    end
  end
  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
                constraints: {path: /(?!(#{I18n.available_locales.join("|")})).*/},
                format: false
  get '', to: redirect("/#{I18n.default_locale}")
end

app/views/admin/_collection_configuration.haml
%div{:id => "#{item_name.pluralize}"}
  .admin.well
    %table.table.borderless{:class => "#{item_name.pluralize}", :style => "width:auto;"}
      %tbody

    = form_for new_item, :url => create_url, :remote => true, :html => {:id => "new_#{item_name}"} do |f|
      %table.table.borderless{:style => "width:200px;"}
        %tr
          %td
            %button.btn.btn-success.btn-xs{:style => 'line-height:1.8;', :type => 'submit'}= t(".#{item_name}.add")
          %td= f.text_field "#{param_name}", :size => 8, :placeholder => placeholder, :id => "#{item_name}_#{param_name}"

%script{:type => 'template/html', :id => "#{item_name}_item_template"}
  %tr
    %td.type{:class => "#{item_name}"} {{ attribute }}
    %td
      = link_to t('defaults.delete'), nil, :class => "delete_#{item_name}"

:coffeescript
  $ ->
    collection = #{collection.to_json.html_safe}
    delete_url = "#{delete_url}"
    el = $(".#{item_name.pluralize} tbody")
    delete_link =  "a.delete_#{item_name}"
    form = $("#new_#{item_name}")
    param_field = $("##{item_name}_#{param_name}")

    _.templateSettings = { interpolate: /\{\{(.+?)\}\}/g }

    item_template = _.template($("##{item_name}_item_template").html())

    if collection.length == 0
      el.append "<tr><td id='empty'>#{ t('.empty')}</td></tr>"
    else
      _.each collection, (item)->
        el.append item_template({attribute : item})

    param_field.attr('size',param_field.attr('placeholder').length)

    form.bind "ajax:before", (e)->
      if param_field.val() == ''
        $('.message_block').html window.flash_error_template({message : "Cannot be blank."})
        false
      else
        $('.message_block').html ""
        true

    form.bind "ajax:success", (e,data,status,xhr)->
      el.append item_template({attribute : data})
      param_field.val('')
      $('td#empty',el).closest('tr').remove()
      $('.message_block').html ''

    el.on 'click', delete_link, (e)->
      e.preventDefault()
      context = $(@).closest('tr')
      id = context.find('.type').html()
      url = delete_url.replace("id",id)
      $.ajax
        url: url
        method: 'delete'
        context: context # becomes 'this' in the callback
        success: (data, status, xhr)->
          this.remove()
          if el.find(".type").length == 0
            el.append "<tr><td id='empty'>#{ t('.empty')}</td></tr>"
          $('.message_block').html('')

app/views/admin/_document_filesize_configuration.haml
%div{:id => "#{context}"}
  .admin.well
    =form_tag update_url, :method => :put, :remote => true, :id => "update_#{context}_filesize" do
      %table.table.borderless.filesize{:style => "width:200px;"}
        %tbody
          %tr
            %td= t('.current_val')
            %td
              %span#filesize #{ param }
              %span MB
          %tr
            %td
              %button.btn.btn-success.btn-xs#change_filesize{:style => 'line-height:1.8;', :type => 'submit'}= t('.change')
            %td
              = text_field_tag :filesize, nil, :size => 6, :placeholder => "e.g. #{param.to_i+2}"
              %span MB

:coffeescript
  $ ->
    $("#update_#{context}_filesize").bind "ajax:success", (e,data,status,xhr)->
      if !_.isEmpty(data.trim())
        $("##{context} span#filesize").text(data)
      $("##{context} input#filesize").val("")